import streamlit as st
import io
from datetime import datetime

# --- Логика конвертации ---
def process_vcf(input_file):
    output_buffer = io.StringIO()
    
    # Шапка как у 23andMe
    current_date = datetime.now().strftime("%Y-%m-%d")
    output_buffer.write(f"# This data file generated by Genotek-to-23andMe Converter\n")
    output_buffer.write(f"# Date: {current_date}\n")
    output_buffer.write(f"# rsid\tchromosome\tposition\tgenotype\n")
    
    # Читаем загруженный файл
    stringio = io.StringIO(input_file.getvalue().decode("utf-8"))
    
    stats = {'written': 0, 'skipped': 0}
    
    for line in stringio:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        
        parts = line.split('\t')
        if len(parts) < 10:
            continue

        # Данные
        chrom, pos, raw_id, ref, alt = parts[0], parts[1], parts[2], parts[3], parts[4]
        genotype_raw = parts[9]

        # 1. Чистим ID
        id_parts = raw_id.split(';')
        clean_rsid = id_parts[0]
        found_rs = False
        for part in id_parts:
            if part.startswith('rs'):
                clean_rsid = part
                found_rs = True
                break
        
        # Если ID это точка или не нашли rs — пропускаем
        if clean_rsid == '.' or (not found_rs and clean_rsid == '.'):
            stats['skipped'] += 1
            continue

        # 2. Чистим хромосому
        clean_chrom = chrom.replace('chr', '')
        
        # 3. Фильтр пустых
        if '.' in genotype_raw and '0' not in genotype_raw and '1' not in genotype_raw:
            stats['skipped'] += 1
            continue
            
        try:
            separator = '|' if '|' in genotype_raw else '/'
            alleles_indices = genotype_raw.split(':')[0].split(separator)
            possible_bases = [ref] + alt.split(',')
            
            final_genotype = ""
            for index in alleles_indices:
                final_genotype += possible_bases[int(index)]
            
            # 4. Фильтр длины (только 1 или 2 буквы)
            if len(final_genotype) > 2:
                stats['skipped'] += 1
                continue
            
            output_buffer.write(f"{clean_rsid}\t{clean_chrom}\t{pos}\t{final_genotype}\n")
            stats['written'] += 1

        except (ValueError, IndexError):
            stats['skipped'] += 1
            continue
            
    return output_buffer.getvalue(), stats

# --- Интерфейс ---
st.set_page_config(page_title="DNA Converter", page_icon="🧬")
st.title("🧬 Genotek to 23andMe")
st.write("Конвертирует VCF файлы в формат, понятный MyHeritage, GEDmatch и другим.")

uploaded_file = st.file_uploader("Загрузи .vcf файл", type="vcf")

if uploaded_file is not None:
    with st.spinner('Обработка...'):
        result_txt, statistics = process_vcf(uploaded_file)
    
    st.success(f"Готово! Сохранено: {statistics['written']} строк.")
    
    new_filename = uploaded_file.name.replace('.vcf', '') + "_23andme.txt"
    st.download_button("📥 Скачать результат", data=result_txt, file_name=new_filename)