import streamlit as st
import io
from datetime import datetime

# --- Логика конвертации ---
def process_vcf(input_file):
    output_buffer = io.StringIO()
    
    # 1. ГЕНЕРАЦИЯ ОРИГИНАЛЬНОЙ ШАПКИ 23ANDME
    # Формат даты: Sat Nov 29 00:00:00 2025
    current_date = datetime.now().strftime("%a %b %d %H:%M:%S %Y")
    
    output_buffer.write(f"# This file was generated by 23andMe at: {current_date}\n")
    output_buffer.write("#\n")
    output_buffer.write("# This file contains raw genotype data, including data that is not used in 23andMe reports.\n")
    output_buffer.write("# This data is suitable only for research, educational, and informational use and not for medical or other use.\n")
    output_buffer.write("# \n")
    output_buffer.write("# Below is a text version of your data.  Fields are TAB-separated\n")
    output_buffer.write("# Each line corresponds to a single SNP.  For each SNP, we provide its identifier \n")
    output_buffer.write("# (an rsid or an internal id), its location on the reference human genome, and the \n")
    output_buffer.write("# genotype call oriented with respect to the plus strand on the human reference sequence.\n")
    output_buffer.write("# We are using reference human assembly build 37 (also known as Annotation Release 104).\n")
    output_buffer.write("# \n")
    output_buffer.write("# rsid\tchromosome\tposition\tgenotype\n")
    
    # Читаем загруженный файл
    stringio = io.StringIO(input_file.getvalue().decode("utf-8"))
    
    stats = {
        'written': 0, 
        'skipped_empty': 0,
        'skipped_indel': 0,
        'skipped_no_id': 0,
        'skipped_bad_format': 0
    }
    
    for line in stringio:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        
        parts = line.split('\t')
        if len(parts) < 10:
            continue

        # Данные
        chrom, pos, raw_id, ref, alt = parts[0], parts[1], parts[2], parts[3], parts[4]
        genotype_raw = parts[9]

        # 2. Чистим ID (удаляем мусор и пустые точки)
        id_parts = raw_id.split(';')
        clean_rsid = id_parts[0]
        found_rs = False
        for part in id_parts:
            if part.startswith('rs'):
                clean_rsid = part
                found_rs = True
                break
        
        # Если ID это точка или не нашли rs — пропускаем
        if clean_rsid == '.' or (not found_rs and clean_rsid == '.'):
            stats['skipped_no_id'] += 1
            continue

        # 3. Чистим хромосому
        clean_chrom = chrom.replace('chr', '')
        
        # 4. Фильтр пустых (./.)
        if '.' in genotype_raw and '0' not in genotype_raw and '1' not in genotype_raw:
            stats['skipped_empty'] += 1
            continue
            
        try:
            separator = '|' if '|' in genotype_raw else '/'
            alleles_indices = genotype_raw.split(':')[0].split(separator)
            possible_bases = [ref] + alt.split(',')
            
            final_genotype = ""
            for index in alleles_indices:
                final_genotype += possible_bases[int(index)]
            
            # 5. Фильтр длины (только 1 или 2 буквы)
            if len(final_genotype) > 2:
                stats['skipped_indel'] += 1
                continue
            
            output_buffer.write(f"{clean_rsid}\t{clean_chrom}\t{pos}\t{final_genotype}\n")
            stats['written'] += 1

        except (ValueError, IndexError):
            stats['skipped_bad_format'] += 1
            continue
            
    return output_buffer.getvalue(), stats

# --- Интерфейс ---
st.set_page_config(page_title="Genotek to 23andMe", page_icon="🧬")
st.title("🧬 Genotek to 23andMe Converter")
st.write("Конвертирует VCF файлы Genotek в оригинальный формат 23andMe (build 37).")

uploaded_file = st.file_uploader("Загрузи .vcf файл", type="vcf")

if uploaded_file is not None:
    with st.spinner('Конвертация...'):
        result_txt, statistics = process_vcf(uploaded_file)
    
    st.success(f"Готово! Обработано {statistics['written']} строк SNP.")
    
    # Показываем детали (можно свернуть)
    with st.expander("Посмотреть статистику очистки"):
        st.write(f"✅ Сохранено строк: {statistics['written']}")
        st.write(f"🗑️ Удалено без ID: {statistics['skipped_no_id']}")
        st.write(f"🗑️ Удалено пустых (./.): {statistics['skipped_empty']}")
        st.write(f"🗑️ Удалено длинных мутаций (Indels): {statistics['skipped_indel']}")

    new_filename = uploaded_file.name.replace('.vcf', '') + "_23andme.txt"
    st.download_button("📥 Скачать готовый файл", data=result_txt, file_name=new_filename)
